dist:                              xenial

language:                          python

python:                            3.7

script:
    - python -m doctest readsettings/__init__.py

jobs:
    include:
        - stage:                   deploy

          python:                  3.7

          if:                      type != pull_request

          install:
              - pip install -r requirements.txt
              - pip install sphinx python-docs-theme

          script:
              - mkdocs build --verbose --clean --strict
              - cd docs-sphinx
              - sphinx-build -b html rst html
              - cp -a $TRAVIS_BUILD_DIR/docs-sphinx/html/. $TRAVIS_BUILD_DIR/site/commands
              - touch $TRAVIS_BUILD_DIR/site/.nojekyll

          deploy:
              provider:            pages
              skip_cleanup:        true
              github_commit:       "Built documentation [skip ci]"
              github_token:        $github_token
              name:                "ROS Bot"
              email:               "richiebendall@gmail.com"
              fqdn:                "readsettings.richie-bendall.ml"
              local_dir:           site

          after_deploy:
              - |
                curl --request DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
                 --header "X-Auth-Email: richiebendall@gmail.com" \
                 --header "X-Auth-Key: ${cf_api_key}" \
                 --header "Content-Type: application/json" \
                 --data '{"purge_everything":true}'

          after_success:           true

        -

          python:                  3.7

          if:                      type != pull_request AND tag IS present

          install:
              - pip install setuptools-git-version

          script:                  true

          deploy:
              - provider:          pypi
                user:              "Richienb"
                password:          $pypi_password
                skip_cleanup:      true
                server:            https://test.pypi.org/legacy/
                distributions:     "sdist bdist_wheel"
                on:
                    all_branches:  true

              - provider:          pypi
                user:              "Richienb"
                password:          $pypi_password
                skip_cleanup:      true
                distributions:     "sdist bdist_wheel"
                on:
                    all_branches:  true

notifications:
    email:                         false
