dist:                           xenial

language:                       python

branch:                         master

python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev

install:
    - pip install -r requirements.txt
    - pip install codecov~=2.0.15

script:
    - coverage run readsettings/__init__.py

after_success:
    - codecov

jobs:
    include:
        - stage:                deploy

          python:               3.7

          if:                   type != pull_request AND tag IS present

          install:
              - pip install -r requirements.txt
              - pip install sphinx sphinx_jekyll_builder

          script:
              - make jekyll
              - echo "remote_theme: Richienb/jekyll-theme-richienb" > build/jekyll/_config.yml

          deploy:
              provider:         pages
              skip_cleanup:     true
              github_commit:    "Built documentation [skip ci]"
              github_token:     $github_token
              name:             "ROS Bot"
              email:            "richiebendall@gmail.com"
              fqdn:             "readsettings.richie-bendall.ml"
              local_dir:        build/jekyll
              on:
                  tags:         true

          after_deploy:
              - |
                curl --request DELETE "https://api.cloudflare.com/client/v4/zones/${cf_zone_id}/purge_cache" \
                 --header "X-Auth-Email: richiebendall@gmail.com" \
                 --header "X-Auth-Key: ${cf_api_key}" \
                 --header "Content-Type: application/json" \
                 --data '{"purge_everything":true}'

          after_success:        true

        -

          python:               3.7

          if:                   type != pull_request AND tag IS present

          install:
              - pip install setuptools-git-version

          script:               true

          deploy:
              - provider:       pypi
                user:           "Richienb"
                password:       $pypi_password
                skip_cleanup:   true
                server:         https://test.pypi.org/legacy/
                distributions:  "sdist bdist_wheel"
                on:
                    tags:       true

              - provider:       pypi
                user:           "Richienb"
                password:       $pypi_password
                skip_cleanup:   true
                distributions:  "sdist bdist_wheel"
                on:
                    tags:       true

          after_success:        true

notifications:
    email:                      false
